[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja = { version = "2.5.0", features = ["loader"] }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempdir = "0.3.7"
